---

version: "3.9"
services:
  postgres:
    image: "${POSTGRES_IMAGE}"
    environment:
      POSTGRES_USER: galaxy
      POSTGRES_PASSWORD: galaxy
  rabbitmq:
    image: "${RABBITMQ_IMAGE}"
  galaxy-web:
    depends_on:
      - "postgres"
      - "rabbitmq"
    image: galaxy-pulsar-dev:galaxy
    build:
      context: "./galaxy/context"
      args:
        GALAXY_IMAGE: "${GALAXY_IMAGE}"
        UID: "${UID}"
        GID: "${GID}"
    #user: "${UID}:${GID}"
    command: /galaxy/.venv/bin/uwsgi --yaml config/galaxy.yml
    volumes: &galaxy_volumes
      - "${GALAXY_ROOT}:/galaxy"
      - "./galaxy/database:/galaxy/database"
      - "./galaxy/venv:/galaxy/.venv:ro"
      - "./galaxy/config:/galaxy/config:ro"
      - "./galaxy/rule.py:/galaxy/lib/galaxy/jobs/rules/rule.py:ro"
    ports:
      - "8080:8080"
  galaxy-job:
    depends_on:
      - "postgres"
      - "rabbitmq"
      - "galaxy-web"
    image: galaxy-pulsar-dev:galaxy
    command: /galaxy/.venv/bin/python3 scripts/galaxy-main --attach-to-pool=job-handlers
    volumes: *galaxy_volumes
  pulsar:
    depends_on:
      - "rabbitmq"
    image: galaxy-pulsar-dev:pulsar
    build:
      context: "./pulsar/context"
      args:
        PULSAR_IMAGE: "${PULSAR_IMAGE}"
        UID: "${UID}"
        GID: "${GID}"
    #command: pulsar-main
    volumes:
      - "${PULSAR_ROOT}:/pulsar"
      - "./pulsar/var:/pulsar/var"
      - "./pulsar/venv:/pulsar/.venv:ro"
      - "./pulsar/config/app.yml:/pulsar/app.yml:ro"
